phone_pattern = Pattern(name='phone_number', regex=r'\d{3}[-\.\s]\d{3}[-\.\s]\d{4}', score=0.9)
    # phone_recognizer = PatternRecognizer(supported_entity='PHONE_NUMBER', patterns=[phone_pattern])
    # debit_pattern = Pattern(name='debit_pattern', regex=r'\d{4}-\d{4}-\d{4}-\d{4}', score=0.9)
    # debit_recognizer = PatternRecognizer(supported_entity='DEBIT_NUMBER', patterns=[debit_pattern])
    # amex_pattern = Pattern(name='amex_pattern', regex=r'\d{4}-\d{6}-\d{5}', score=0.9)
    # amex_recognizer = PatternRecognizer(supported_entity='AMEX', patterns=[amex_pattern])
    # ssn_pattern = Pattern(name='ssn_pattern', regex=r'(\b\d{3}-?\d{2}-?\d{4}\b)', score=0.9)
    # ssn_recognizer = PatternRecognizer(supported_entity='SS_NUMBER', patterns=[ssn_pattern])
    # email_pattern = Pattern(name='email_pattern', regex=r'[\w\.-]+@[\w\.-]+', score=0.9)
    # email_recognizer = PatternRecognizer(supported_entity='EMAIL_ADDRESS', patterns=[email_pattern])
    # insta_pattern = Pattern(name='insta_pattern', regex=r'@\b[\w.]+', score=0.9)
    # insta_recognizer = PatternRecognizer(supported_entity='INSTA_ACCOUNT', patterns=[insta_pattern])